name: Telegram Mirror Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Restart tiap 6 jam

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GOFILE_API_KEY: ${{ secrets.GOFILE_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Start..."
          python bot.py
